---
    - name: update cash
      apt:
        update_cache: yes

    - name: create directory
      file:
        path: "{{zabbix_agent_dest}}"
        state: directory
        mode: "u=rwx,g=rwx,o=rwx"

    - name: download zabbix
      get_url:
        url: "{{zabbix_agent_url}}"
        dest: "{{zabbix_agent_dest}}"

    - name: install packages
      apt:
        deb: "{{zabbix_agent_dest}}{{zabbix_agent_deb}}"
        update_cache: yes

    - name: install zabbix agent
      apt:
        name: zabbix-agent2
        state: present

    - name: config zabbix agent
      template:
        src: zabbix_agent.j2
        dest: /etc/zabbix/zabbix_agent2.conf

    - name: enable and start zabbix-agent
      systemd:
        name: zabbix-agent2
        enabled: yes
      systemd:
        name: zabbix-agent2
        state: started